name: i2k-2020
channels:
  - conda-forge
  - defaults
dependencies:
  - imglyb=1.0.0
  - itk
  - itkwidgets=0.32.0
  - ipywidgets=7.5.1
  - jgo=1.0.0
  - jpype1
  - maven=3.6.0
  - napari=0.4.2
  - notebook=6.1.5
  - numpy=1.19.4
  - openjdk=8.0.265
  - pip
  - python=3.7.8
  - scikit-image
  - scipy
  - scyjava=1.1.0
  - pip:
    - git+https://github.com/jpype-project/jpype.git@bffe61e161b0d3f9825664a4815b35a82cbe9919#egg=jpype1
    - git+https://github.com/imagej/pyimagej.git@9702f94f2f11865d02de63bc82ead47ce510ab1b#egg=pyimagej
