name: i2k-2020
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets=7.5.1
  - jgo=1.0.0
  - jpype1
  - maven=3.6.0=0
  - notebook=6.1.5
  - numpy=1.19.4
  - openjdk=8.0.265
  - pip
  - python=3.7.8
  - scikit-image=0.17.2
  - scipy=1.5.2
  - pip:
    - dependencies/jpype1
    - dependencies/scyjava
    - dependencies/imglyb
    - dependencies/pyimagej
